# Generated by Django 5.2.5 on 2025-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='is_published',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='fees',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='net_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='price_per_unit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='total_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='goldwallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rialtransaction',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rialwallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
