# Generated by Django 5.2.5 on 2025-08-19 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bankaccount_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rialtransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bankaccount'),
        ),
    ]
