# Generated by Django 5.2.5 on 2025-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userverification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='image_url',
        ),
        migrations.AddField(
            model_name='license',
            name='image',
            field=models.ImageField(default=1, upload_to='licenses/'),
            preserve_default=False,
        ),
    ]
