# Generated by Django 5.2.5 on 2025-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_license_image_url_license_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_buy_count', models.PositiveIntegerField(default=0)),
                ('ma_sell_count', models.PositiveIntegerField(default=0)),
                ('ma_neutral_count', models.PositiveIntegerField(default=0)),
                ('osc_buy_count', models.PositiveIntegerField(default=0)),
                ('osc_sell_count', models.PositiveIntegerField(default=0)),
                ('osc_neutral_count', models.PositiveIntegerField(default=0)),
                ('summary_buy_count', models.PositiveIntegerField(default=0)),
                ('summary_sell_count', models.PositiveIntegerField(default=0)),
                ('summary_neutral_count', models.PositiveIntegerField(default=0)),
                ('summary_signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('NEUTRAL', 'Neutral'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], default='NEUTRAL', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
