# Generated by Django 5.2.5 on 2025-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_technicalanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalanalysis',
            name='ma_signal',
            field=models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('NEUTRAL', 'Neutral'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], default='NEUTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='osc_signal',
            field=models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('NEUTRAL', 'Neutral'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], default='NEUTRAL', max_length=20),
        ),
    ]
