# Generated by Django 5.2.5 on 2025-08-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_technicalanalysis_ma_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalanalysis',
            name='timeframe',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
