# Generated by Django 5.2.5 on 2025-09-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_technicalanalysis_timeframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=10, unique=True)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('trained_at', models.DateTimeField(auto_now=True)),
                ('model_accuracy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
