# Generated by Django 5.2.5 on 2025-09-12 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_priceprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceprediction',
            name='confidence',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceprediction',
            name='signal',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
